src/main/java/ci/todolist/TodoListMB.java
package ci.todolist;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;

@ManagedBean
public class TodoListMB {

    @Inject
    private TodoItemRepository repository;

    @PostConstruct
    public void initialize() {
        if (repository.isEmpty()) {
            repository.create("Aprender TDD :)");
            repository.create("Aprender JPA o/");
            repository.create("Aprender EJB ;)");
            repository.create("Aprender JSF \\o/");
        }
    }

    public Long getTodosCount() {
        return repository.count();
    }

    public List<TodoItem> getTodos() {
        return repository.getAll();
    }

}

src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"></link>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</h:head>
<h:body>
    <div class="container">
        <h:dataTable value="#{todoListMB.todos}" var="todo"
            styleClass="highlight">
            <h:column>
                <f:facet name="header">Id</f:facet>
                #{todo.id}
            </h:column>

            <h:column>
                <f:facet name="header">Description</f:facet>
                #{todo.description}
            </h:column>
        </h:dataTable>

        <div>
            Total de tarefas:
            <h:outputText value="#{todoListMB.todosCount}" />
        </div>
    </div>
</h:body>
</html>